// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjjV7rfp49I0NSSSWoQMIhDSJ7FxVpHpw',
    appId: '1:147106568496:web:e299a2835457d06ba850f5',
    messagingSenderId: '147106568496',
    projectId: 'flutterdemo-d2ced',
    authDomain: 'flutterdemo-d2ced.firebaseapp.com',
    storageBucket: 'flutterdemo-d2ced.firebasestorage.app',
    measurementId: 'G-THHRY936BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVcH3IYPdx3AqiQO6rQBCr9Tk9PxMkvU',
    appId: '1:147106568496:android:02b152516842dd92a850f5',
    messagingSenderId: '147106568496',
    projectId: 'flutterdemo-d2ced',
    storageBucket: 'flutterdemo-d2ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDc6x620inRMwRoiYfFcRIy-bx_Nxgw1Q',
    appId: '1:147106568496:ios:627c4896a5dbbdc2a850f5',
    messagingSenderId: '147106568496',
    projectId: 'flutterdemo-d2ced',
    storageBucket: 'flutterdemo-d2ced.firebasestorage.app',
    iosBundleId: 'com.example.crudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDc6x620inRMwRoiYfFcRIy-bx_Nxgw1Q',
    appId: '1:147106568496:ios:627c4896a5dbbdc2a850f5',
    messagingSenderId: '147106568496',
    projectId: 'flutterdemo-d2ced',
    storageBucket: 'flutterdemo-d2ced.firebasestorage.app',
    iosBundleId: 'com.example.crudFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjjV7rfp49I0NSSSWoQMIhDSJ7FxVpHpw',
    appId: '1:147106568496:web:f1f1c960f82f7257a850f5',
    messagingSenderId: '147106568496',
    projectId: 'flutterdemo-d2ced',
    authDomain: 'flutterdemo-d2ced.firebaseapp.com',
    storageBucket: 'flutterdemo-d2ced.firebasestorage.app',
    measurementId: 'G-5S3K8312S5',
  );
}
